export const ALL_BOOKING_REQUEST = "ALL_BOOKING_REQUEST";
export const ALL_BOOKING_SUCCESS = "ALL_BOOKING_SUCCESS";
export const ALL_BOOKING_FAIL = "ALL_BOOKING_FAIL";

export const MECHANIC_BOOKING_REQUEST = "MECHANIC_BOOKING_REQUEST";
export const MECHANIC_BOOKING_SUCCESS = "MECHANIC_BOOKING_SUCCESS";
export const MECHANIC_BOOKING_FAIL = "MECHANIC_BOOKING_FAIL";

export const NEW_BOOKING_REQUEST = "NEW_BOOKING_REQUEST";
export const NEW_BOOKING_SUCCESS = "NEW_BOOKING_SUCCESS";
export const NEW_BOOKING_FAIL = "NEW_BOOKING_FAIL";
export const NEW_BOOKING_RESET = "NEW_BOOKING_RESET";

export const DELETE_BOOKING_REQUEST = "DELETE_BOOKING_REQUEST";
export const DELETE_BOOKING_SUCCESS = "DELETE_BOOKING_SUCCESS";
export const DELETE_BOOKING_RESET = "DELETE_BOOKING_RESET";
export const DELETE_BOOKING_FAIL = "DELETE_BOOKING_FAIL";

export const UPDATE_BOOKING_REQUEST = "UPDATE_BOOKING_REQUEST";
export const UPDATE_BOOKING_SUCCESS = "UPDATE_BOOKING_SUCCESS";
export const UPDATE_BOOKING_RESET = "UPDATE_BOOKING_RESET";
export const UPDATE_BOOKING_FAIL = "UPDATE_BOOKING_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
