export const ALL_MECHANIC_REQUEST = "ALL_MECHANIC_REQUEST";
export const ALL_MECHANIC_SUCCESS = "ALL_MECHANIC_SUCCESS";
export const ALL_MECHANIC_FAIL = "ALL_MECHANIC_FAIL";

export const MECHANIC_DETAILS_REQUEST = "MECHANIC_DETAILS_REQUEST";
export const MECHANIC_DETAILS_SUCCESS = "MECHANIC_DETAILS_SUCCESS";
export const MECHANIC_DETAILS_FAIL = "MECHANIC_DETAILS_FAIL";

export const NEW_MECHANIC_REVIEW_REQUEST = "NEW_MECHANIC_REVIEW_REQUEST";
export const NEW_MECHANIC_REVIEW_SUCCESS = "NEW_MECHANIC_REVIEW_SUCCESS";
export const NEW_MECHANIC_REVIEW_RESET = "NEW_MECHANIC_REVIEW_RESET";
export const NEW_MECHANIC_REVIEW_FAIL = "NEW_MECHANIC_REVIEW_FAIL";

export const UPDATE_MECHANIC_REQUEST = "UPDATE_MECHANIC_REQUEST";
export const UPDATE_MECHANIC_SUCCESS = "UPDATE_MECHANIC_SUCCESS";
export const UPDATE_MECHANIC_RESET = "UPDATE_MECHANIC_RESET";
export const UPDATE_MECHANIC_FAIL = "UPDATE_MECHANIC_FAIL";

export const ALL_MECHANIC_REVIEW_REQUEST = "ALL_MECHANIC_REVIEW_REQUEST";
export const ALL_MECHANIC_REVIEW_SUCCESS = "ALL_MECHANIC_REVIEW_SUCCESS";
export const ALL_MECHANIC_REVIEW_FAIL = "ALL_MECHANIC_REVIEW_FAIL";

export const ALL_MECHANIC_PRODUCTS_REQUEST = "ALL_MECHANIC_BOOKING_REQUEST";
export const ALL_MECHANIC_PRODUCTS_SUCCESS = "ALL_MECHANIC_BOOKING_SUCCESS";
export const ALL_MECHANIC_PRODUCTS_FAIL = "ALL_MECHANIC_BOOKING_FAIL";

export const DELETE_MECHANIC_REVIEW_REQUEST = "DELETE_MECHANIC_REVIEW_REQUEST";
export const DELETE_MECHANIC_REVIEW_SUCCESS = "DELETE_MECHANIC_REVIEW_SUCCESS";
export const DELETE_MECHANIC_REVIEW_RESET = "DELETE_MECHANIC_REVIEW_RESET";
export const DELETE_MECHANIC_REVIEW_FAIL = "DELETE_MECHANIC_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
